### ISSUE TITLE
Upgrade dependency to latest requests 2.2.1

### ISSUE THREAD

**Issue by javouhey** [mozilla/PyHawk#25]
I notice that your dev requirements file states that you are depending on requests 1.2.0

I ran the `sample_client.py` against `requests` 2.2.1 and it bombed with this error:
https://gist.github.com/javouhey/11240251

I checked the [Custom Header docs](http://docs.python-requests.org/en/v1.2.3/user/quickstart/#custom-headers) for `requests` v1.2.3 and it expects the headers argument to be a dictionary.

```
res = requests.get(url, data=params, headers=headers)
```

**Comment by kumar303** [comment]
Hi, thanks for taking the time to submit an issue. The PyHawk library is no longer maintained so we can't respond to issues. Please consider these alternatives:

* https://github.com/kumar303/mohawk
* https://github.com/mozilla-services/hawkauthlib
