### ISSUE TITLE
Add syntax highlighting to code blocks in README

### ISSUE THREAD

**Issue by itsnauman** [mozilla/PyHawk#26]
Syntax highlighting to the code in `README.md` will make it more readable :smiley:

**Comment by kumar303** [comment]
Hi, thanks for taking the time to submit an issue. The PyHawk library is no longer maintained so we can't respond to issues. Please consider these alternatives:

* https://github.com/kumar303/mohawk
* https://github.com/mozilla-services/hawkauthlib
