### ISSUE TITLE
Replace awkward dictionary key checking

### ISSUE THREAD

**Issue by ozten** [mozilla/PyHawk#4]
In many places, I do a check for a key in a dict.

As @ludwigkraatz pointed out, we should instead use:

```
get('hash', None)
```

Go through and make these blocks Pythonic.

**Comment by kumar303** [comment]
Hi all! Since PyHawk is no longer maintained I'm updating everything to make it obvious. Here are some alternatives:

* https://github.com/kumar303/mohawk
* https://github.com/mozilla-services/hawkauthlib
